### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by llongour** [datagora-erasme/itineraire_fraicheur#68]
Great work ! I'd like to try deploying it, but it looks like there's no license on your repository yet.

**Comment by aangelot** [comment]
Thanks for your feedback!

We have just added an MIT license, allowing the project to be replicated (for Strabsourg Métropole, is that it?)

If you would like a call to talk about the project, I remain available. Please mail me at aangelot@grandlyon.com

**Comment by llongour** [comment]
Sure ! Thank you very much 😄
